In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

In [2]:
data = pd.read_csv('data_v3/train_data_v3.csv', parse_dates=True)

In [4]:
data.drop(data[data['label']=='unclassified'].index, inplace=True)
data

                       time           Measure      kWh           label
3       2022-01-03 00:00:00     AB3 - Main 3L  36.7500  Non-production
5       2022-01-03 00:00:00  Sub - Feeder F02  64.2500  Non-production
8       2022-01-03 00:00:00     BS4 - Main 4R  19.2500  Non-production
12      2022-01-03 00:00:00     BS1 - Main 1L  31.7500  Non-production
24      2022-01-03 00:15:00     BS4 - Main 4R  19.2500  Non-production
...                     ...               ...      ...             ...
652391  2022-11-13 23:30:00     BS1 - Main 1L  34.6250  Non-production
652392  2022-11-13 23:30:00     AB3 - Main 3L  30.8750  Non-production
652404  2022-11-13 23:45:00     BS1 - Main 1L  34.3125  Non-production
652405  2022-11-13 23:45:00     BS4 - Main 4R  30.8750  Non-production
652415  2022-11-13 23:45:00     AB3 - Main 3L  31.0625  Non-production

[81312 rows x 4 columns]